### ISSUE TITLE
Velero can't be installed when S3 bucket does not define an endpoint correctly

### ISSUE THREAD

**Issue by mazzy89** [flanksource/platform-cli#156]
During this PR https://github.com/flanksource/platform-cli/pull/139 I have noticed that this configuration

```yaml
s3:
  bucket: flanksource-lab
  access_key: $AWS_ACCESS_KEY_ID
  secret_key: $AWS_SECRET_ACCESS_KEY
  region: us-east1
velero:
  bucket: velero
```

triggers an error like this

```
FATA[0052] Error installing velero: install: failed to get S3 client: Endpoint url cannot have fully qualified paths. 
```

and also this configuration leads to an error:

```yaml
s3:
  endpoint: http://minio.minio.svc:9000
  bucket: flanksource-lab
  access_key: $AWS_ACCESS_KEY_ID
  secret_key: $AWS_SECRET_ACCESS_KEY
  region: us-east1
velero:
  bucket: velero
```

like this

```
FATA[0056] Error installing velero: install: failed to get S3 client: address http://minio.minio.svc:9000: too many colons in address 
```
