### ISSUE TITLE
Deploy elasticsearch

### ISSUE THREAD

**Issue by moshloop** [flanksource/platform-cli#231]
Deploys a default configuration of elasticsearch, 

```yaml
elasticsearch:
   version: 7.6.0
   mem: 2G
   replicas: 3
   persistence:
      size: 30Gb
```
