### ISSUE TITLE
Support multiple filebeat instances

### ISSUE THREAD

**Issue by moshloop** [flanksource/platform-cli#283]
```
filebeat:
 - elasticsearch: ....
    namespaces:
      exclude:
- logstash: ...
  namespaces: 
    include: ..
```
+ add support for specifying a logstash server as output
